"""follower

Revision ID: 52091fe12740
Revises: c613dacd1b96
Create Date: 2020-07-24 01:31:56.199123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52091fe12740'
down_revision = 'c613dacd1b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
